use std::path::Path;

use fst_writer::{
    FstFileType, FstInfo, FstScopeType, FstSignalType, FstVarDirection, FstVarType, open_fst,
};

/// Write the canonical deterministic tiny FST fixture.
///
/// The fixed date/version and event order are intentional: tests compare the
/// generated bytes with the committed fixture to catch writer or recipe drift.
pub fn write_tiny_fst(path: &Path) {
    let info = FstInfo {
        start_time: 0,
        timescale_exponent: -9,
        version: "vcd_tools_rs test fixture".to_string(),
        date: "2025-01-01".to_string(),
        file_type: FstFileType::Verilog,
    };
    let mut header = open_fst(path, &info).expect("create FST fixture");
    header
        .scope("top", "top", FstScopeType::Module)
        .expect("scope");
    let signal = header
        .var(
            "a",
            FstSignalType::bit_vec(1),
            FstVarType::Logic,
            FstVarDirection::Implicit,
            None,
        )
        .expect("signal");
    header
        .var(
            "a_alias",
            FstSignalType::bit_vec(1),
            FstVarType::Logic,
            FstVarDirection::Implicit,
            Some(signal),
        )
        .expect("alias");
    header.up_scope().expect("close scope");
    let mut body = header.finish().expect("finish header");
    body.signal_change(signal, b"0").expect("initial value");
    body.time_change(5).expect("time");
    body.signal_change(signal, b"1").expect("changed value");
    body.finish().expect("finish body");
}
